// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_auth_signin from "./routes/api/auth/signin.ts";
import * as $dashboard from "./routes/dashboard.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $signin from "./routes/signin.tsx";
import * as $utils_supabase from "./routes/utils/supabase.ts";
import * as $CardIsland from "./islands/CardIsland.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import * as $NavbarIsland from "./islands/NavbarIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/auth/signin.ts": $api_auth_signin,
    "./routes/dashboard.ts": $dashboard,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/signin.tsx": $signin,
    "./routes/utils/supabase.ts": $utils_supabase,
  },
  islands: {
    "./islands/CardIsland.tsx": $CardIsland,
    "./islands/LoginForm.tsx": $LoginForm,
    "./islands/NavbarIsland.tsx": $NavbarIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
